### ISSUE TITLE
Build instructions for Linux incomplete

### ISSUE THREAD

**Issue by nefiertsarbez** [MAX-Reloaded/maxr#23]
In wiki page section https://github.com/maxr-dot-org/maxr/wiki/How-to-build-on-linux#build-steps

information is missing that submodules needs to be cloned as well, either with

`git clone --recurse-submodules https://github.com/maxr-dot-org/maxr.git` 

or with

```
git clone https://github.com/maxr-dot-org/maxr.git
cd maxr
git submodule update --init --recursive
```

Otherwide the `submodules/<submodulename>` subdirectories remain empy and the `cmake ..` step in build instructions complains, for example with this error message: 

```
CMake Error at CMakeLists.txt:63 (include):
  include could not find load file:

    doctest

-- Setting cpp define GIT_DESC to release-0.2.16
CMake Error at CMakeLists.txt:120 (doctest_discover_tests):
  Unknown CMake command "doctest_discover_tests".

-- Configuring incomplete, errors occurred!

```

Used version https://github.com/maxr-dot-org/maxr/commit/a5cf165289e5ad3a5803d8fc5b6fd4e5cbdfac81

**Comment by Jarod42** [comment]
Changed. Thanks for feedback.
