### ISSUE TITLE
maxr-0.2.17 not starting

### ISSUE THREAD

**Issue by hammerer77** [MAX-Reloaded/maxr#24]
hello,
i installed the new version, but the Programm is not starting, when i install the programm in a new folder, by the first starting its missing the CrashRpt1403.dll.
i copy the file from a nother installation, the error message comes not again, but the gmae ist not starting

has somebody the same error?

thanks

**Comment by Jarod42** [comment]
Indeed, it seems to have error in installer about CrashRpt1403 (.dll and other files are missing) :-/
Rebuilding an installer to fix it soon.

**Comment by Jarod42** [comment]
Should be fixed now.
Installer/release has been updated.
Tag has been moved.

**Comment by hammerer77** [comment]
hello

now i installed the new file from you, the setup will finished, but the game will not starting,
i get now error message

does somebody play the new version?

thanks

**Comment by Jarod42** [comment]
Which error message do you get?
I tried the installer and launch the game without error on my side :-/

**Comment by hammerer77** [comment]
sorry there was a write error in my tab, there is "no" errormessage, the setup will finshed with no errormessages, but i cannot start the new game, i have already installed the old 0.2-16 Version in a nother Folder , this Gameversion will start and working
[resinstaller.log](https://github.com/user-attachments/files/17688484/resinstaller.log)

**Comment by Jarod42** [comment]
ok, you have issue with resinstaller.
You seems to pass wrong argument and/or you don't have write access to output folder.

**Comment by hammerer77** [comment]
i looked in the windows ecents: here i see an error with MSVCP140.dll, i reinstall the vb runteime https://aka.ms/vs/17/release/vc_redist.x86.exe, now its running, thanks for your help
